apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: crawl
spec:
  minReplicas: 1
  maxReplicas: 1000
  metrics:
    - external:
        metricName: pubsub.googleapis.com|subscription|num_undelivered_messages
        metricSelector:
          matchLabels:
            resource.labels.subscription_id: crawl-batches-subscription
        targetAverageValue: "2"
      type: External
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: crawl
