const IMPORT_STATUS_PENDING = 'pending'
const IMPORT_STATUS_RUNNING = 'running'
const IMPORT_STATUS_COMPLETED = 'completed'
const IMPORT_STATUS_ERROR = 'error'

module.exports = {
  IMPORT_STATUS_PENDING,
  IMPORT_STATUS_RUNNING,
  IMPORT_STATUS_COMPLETED,
  IMPORT_STATUS_ERROR,
}
