version: '3.7'
services:
  orchestrator:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
      - '8080:8080'
    command: npm run start-orchestrator
  crawl:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
      - '8081:8080'
    command: npm run start-crawl
  crawl-result:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
      - '8082:8080'
    command: npm run start-crawlResult
