version: '3.7'
services:
  orchestrator:
    build:
      context: ./
      dockerfile: docker/orchestrator/Dockerfile
    ports:
      - '8080:8080'
    command: npm run start-orchestrator
  crawl:
    build:
      context: ./
      dockerfile: docker/crawl/Dockerfile
    ports:
      - '8081:8080'
    command: npm run start-crawl
  crawlresult:
    build:
      context: ./
      dockerfile: docker/crawlResult/Dockerfile
    ports:
      - '8082:8080'
    command: npm run start-crawlResult
